import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';

// THIS IS A COMMENT ! "2nd comment 3rd push dfds WAHAJ"
//ALI

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
